<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Soenneker.Hashing.Argon2" Version="4.0.746" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\Utils\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Analogix_Backend_App.Domain\Analogix_Backend_App.Domain.csproj" />
  </ItemGroup>

</Project>
