// <auto-generated />
using System;
using Analogix_Backend_App.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Analogix_Backend_App.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326110556_updateDbHome")]
    partial class updateDbHome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatorId");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int")
                        .HasColumnName("MaxParticipants");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id")
                        .HasName("PK_Events");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("IX_Events_CreatorId");

                    b.HasIndex("Location")
                        .HasDatabaseName("IX_Events_Location");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_Events_StartDate");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.EventFaq", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("AnsweredUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AskedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AnsweredUserId")
                        .HasDatabaseName("IX_EventFaqs_AnsweredUserId");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("IX_EventFaqs_AuthorUserId");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_EventFaqs_EventId");

                    b.ToTable("EventFaqs", (string)null);
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.EventSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ResponseAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ResponseAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_EventSubscriptions");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_EventSubscriptions_Status");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_EventSubscriptions_EventId_UserId");

                    b.ToTable("EventSubscriptions", (string)null);
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.GameTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NormalizedName");

                    b.HasKey("Id")
                        .HasName("PK_GameTags");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_GameTags_NormalizedName");

                    b.ToTable("GameTags", (string)null);
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.PlayerProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteGames")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MasteryLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("PK_PlayerProfiles");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlayerProfiles_UserId");

                    b.ToTable("PlayerProfiles", (string)null);
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.PlayerReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ReportedPlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReporterId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ReviewerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_PlayerReports");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_PlayerReports_EventId");

                    b.HasIndex("ReportStatus")
                        .HasDatabaseName("IX_PlayerReports_ReportStatus");

                    b.HasIndex("ReportedPlayerId")
                        .HasDatabaseName("IX_PlayerReports_ReportedPlayerId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("EventId", "ReporterId", "ReportedPlayerId")
                        .HasDatabaseName("IX_PlayerReports_Event_Reporter_ReportedPlayer");

                    b.ToTable("PlayerReports", (string)null);
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.Rating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long>("RaterUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_Ratings_Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("RaterUserId");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_Ratings_TargetUserId");

                    b.HasIndex("EventId", "RaterUserId", "TargetType")
                        .HasDatabaseName("IX_Ratings_EventId_RaterUserId_TargetType")
                        .HasFilter("[TargetUserId] IS NULL");

                    b.HasIndex("EventId", "RaterUserId", "TargetType", "TargetUserId")
                        .HasDatabaseName("IX_Ratings_EventId_RaterUserId_TargetType_TargetUserId")
                        .HasFilter("[TargetUserId] IS NOT NULL");

                    b.ToTable("Ratings", (string)null);
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("User")
                        .HasColumnName("Role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EventGameTag", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long>("GameTagId")
                        .HasColumnType("bigint");

                    b.HasKey("EventId", "GameTagId")
                        .HasName("PK_EventGameTag");

                    b.HasIndex("GameTagId");

                    b.ToTable("EventGameTags", (string)null);
                });

            modelBuilder.Entity("PlayerProfileGameTag", b =>
                {
                    b.Property<long>("PlayerProfileId")
                        .HasColumnType("bigint");

                    b.Property<long>("GameTagId")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerProfileId", "GameTagId")
                        .HasName("PK_PlayerProfileGameTags");

                    b.HasIndex("GameTagId");

                    b.ToTable("PlayerProfileGameTags", (string)null);
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.Event", b =>
                {
                    b.HasOne("Analogix_Backend_App.Domain.Models.User", "Creator")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Events_Users_CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.EventFaq", b =>
                {
                    b.HasOne("Analogix_Backend_App.Domain.Models.User", "AnsweredUser")
                        .WithMany("AnsweredFaqs")
                        .HasForeignKey("AnsweredUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_EventFaqs_Users_AnsweredUserId");

                    b.HasOne("Analogix_Backend_App.Domain.Models.User", "AuthorUser")
                        .WithMany("AskedFaqs")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventFaqs_Users_AuthorUserId");

                    b.HasOne("Analogix_Backend_App.Domain.Models.Event", "Event")
                        .WithMany("EventFaq")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EventFaqs_Events_EventId");

                    b.Navigation("AnsweredUser");

                    b.Navigation("AuthorUser");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.EventSubscription", b =>
                {
                    b.HasOne("Analogix_Backend_App.Domain.Models.Event", "Event")
                        .WithMany("Subscriptions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EventSubscriptions_Events_EventId");

                    b.HasOne("Analogix_Backend_App.Domain.Models.User", "User")
                        .WithMany("EventSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventSubscriptions_Users_UserId");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.PlayerProfile", b =>
                {
                    b.HasOne("Analogix_Backend_App.Domain.Models.User", "User")
                        .WithOne("PlayerProfile")
                        .HasForeignKey("Analogix_Backend_App.Domain.Models.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerProfiles_Users_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.PlayerReport", b =>
                {
                    b.HasOne("Analogix_Backend_App.Domain.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerReports_Event");

                    b.HasOne("Analogix_Backend_App.Domain.Models.User", "ReportedPlayer")
                        .WithMany()
                        .HasForeignKey("ReportedPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerReports_ReportedPlayer");

                    b.HasOne("Analogix_Backend_App.Domain.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlayerReports_Reporter");

                    b.HasOne("Analogix_Backend_App.Domain.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_PlayerReports_Reviewer");

                    b.Navigation("Event");

                    b.Navigation("ReportedPlayer");

                    b.Navigation("Reporter");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.Rating", b =>
                {
                    b.HasOne("Analogix_Backend_App.Domain.Models.Event", "Event")
                        .WithMany("Ratings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_Events_EventId");

                    b.HasOne("Analogix_Backend_App.Domain.Models.User", "RaterUser")
                        .WithMany("GivenRatings")
                        .HasForeignKey("RaterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_Users_RaterUserId");

                    b.HasOne("Analogix_Backend_App.Domain.Models.User", "TargetUser")
                        .WithMany("ReceivedRatings")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Ratings_Users_TargetUserId");

                    b.Navigation("Event");

                    b.Navigation("RaterUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("EventGameTag", b =>
                {
                    b.HasOne("Analogix_Backend_App.Domain.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EventGameTag_Events_EventId");

                    b.HasOne("Analogix_Backend_App.Domain.Models.GameTag", null)
                        .WithMany()
                        .HasForeignKey("GameTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EventGameTag_GameTags_GameTagId");
                });

            modelBuilder.Entity("PlayerProfileGameTag", b =>
                {
                    b.HasOne("Analogix_Backend_App.Domain.Models.GameTag", null)
                        .WithMany()
                        .HasForeignKey("GameTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProfileGameTags_GameTags_GameTagId");

                    b.HasOne("Analogix_Backend_App.Domain.Models.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProfileGameTags_PlayerProfiles_PlayerProfileId");
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.Event", b =>
                {
                    b.Navigation("EventFaq");

                    b.Navigation("Ratings");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Analogix_Backend_App.Domain.Models.User", b =>
                {
                    b.Navigation("AnsweredFaqs");

                    b.Navigation("AskedFaqs");

                    b.Navigation("CreatedEvents");

                    b.Navigation("EventSubscriptions");

                    b.Navigation("GivenRatings");

                    b.Navigation("PlayerProfile");

                    b.Navigation("ReceivedRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
